request:
  host: "walmart.p.rapidapi.com"
  path: "/products/list"
  
db:
  database: "testdbc45" 
  username: "c4ebatch5" 
  password : "c4ebatch@5"
  host : "db4free.net" 
  port : "3306"
  
request-stores:
  host: "walmart.p.rapidapi.com"
  path: "/stores/list"